<template>
  <div class="import-wallet login-wrapper no-outer-pad">
    <div class="login-header">
      <LogoWallet />
    </div>
    <div class="import-wallet_top" id="import-wallet_top">
      <h2>{{ $t('pages.onboarding.import.unlockWallet') }}</h2>
      <p v-if="currentStep === 'seedphrase'">
        {{ $t('pages.onboarding.import.enterSeedPhrase') }}
      </p>
      <p v-else-if="currentStep === 'seedtype'">
        Choose the seed type
      </p>
      <p v-else>
        Input your custom derivation path
      </p>
    </div>
    <div class="import-wallet_bottom" v-if="currentStep === 'seedphrase'">
      <div class="btn-group" id="word_button_group">
        <button
          :class="{ active: numWords === 12 }"
          class="btn btn-option"
          id="twelve_words_option"
          @click="setMnemonicLength(12)"
        >
          {{ $t('pages.onboarding.import.words', { words: 12 }) }}
        </button>
        <button
          :class="{ active: numWords === 24 }"
          class="btn btn-option"
          id="twenty_four_words_option"
          @click="setMnemonicLength(24)"
        >
          {{ $t('pages.onboarding.import.words', { words: 24 }) }}
        </button>
      </div>
      <form class="form import-wallet_seed" autocomplete="off">
        <div v-for="(e, n) in numWords" :key="n">
          <input
            type="text"
            class="form-control form-control-sm"
            id="import_wallet_word"
            v-model="wordList[n]"
            autocomplete="off"
            required
          />
        </div>
      </form>
    </div>
    <div class="import-wallet_bottom" style="text-align: left" v-else-if="currentStep === 'seedtype'">
      <div class="custom-control custom-radio">
        <input
          class="custom-control-input"
          type="radio"
          name="seed_type_option"
          id="option_circbit_seed"
          v-model="seedtype"
          value="circbit"
        />
        <label class="custom-control-label" for="option_circbit_seed">
          Circbit seed (generated by Circbit app)
        </label>
      </div>
      <div class="custom-control custom-radio">
        <input
          class="custom-control-input"
          type="radio"
          name="seed_type_option"
          id="option_bip39_standard_seed"
          v-model="seedtype"
          value="bip39_standard"
        />
        <label class="custom-control-label" for="option_bip39_standard_seed">
          Standard BIP39 seed (generated by Yaswap wallet)
        </label>
      </div>
      <div class="custom-control custom-radio">
        <input
          class="custom-control-input"
          type="radio"
          name="seed_type_option"
          id="option_bip39_custom_seed"
          v-model="seedtype"
          value="bip39_custom"
        />
        <label class="custom-control-label" for="option_bip39_custom_seed">
          BIP39 seed with custom derivation path
        </label>
      </div>
    </div>
    <div class="import-wallet_bottom" style="text-align: left" v-else>
      <div class="derivation-path-form-control">
        <input type="text" v-model="customDerivationPath" placeholder="m/84'/0'/0'" />
      </div>
    </div>
    <div class="footer-container bg-white">
      <div class="footer-content">
        <button
          id="import_wallet_cancel_button"
          class="btn btn-light btn-outline-primary btn-lg btn-footer btn-icon"
          @click="back"
        >
          {{ $t('common.back') }}
        </button>
        <button
          id="import_wallet_continue_button"
          class="btn btn-primary btn-lg btn-footer ml-2"
          :disabled="nextDisabled"
          @click="next"
        >
          {{ $t('common.continue') }}
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import { mapState } from 'vuex'
import LogoWallet from '@/assets/icons/logo_wallet.svg'
import { validateMnemonic } from 'bip39'

export default {
  components: {
    LogoWallet
  },
  data: function () {
    return {
      currentStep: 'seedphrase',
      wordList: Array(12).fill(''),
      numWords: 12,
      seedtype: 'circbit',
      customDerivationPath: null,
    }
  },
  updated: function () {},
  watch: {
    wordList: function (newList) {
      var words = newList[0].split(' ')
      if (words.length === this.numWords) {
        for (var m = 0; m < words.length; m++) {
          this.wordList[m] = words[m]
        }
      }
    }
  },
  computed: {
    ...mapState(['wallets', 'activeWalletId']),
    wallet() {
      return this.wallets.find((wallet) => wallet.id === this.activeWalletId)
    },
    validMnemonic() {
      return (
        (this.mnemonic.split(' ').length === 12 || this.mnemonic.split(' ').length === 24) &&
        validateMnemonic(this.mnemonic)
      )
    },
    nextDisabled() {
      return this.mnemonic === '' || !this.validMnemonic
    },
    mnemonic() {
      return this.wordList.join(' ')
    }
  },
  methods: {
    back() {
      switch (this.currentStep) {
        case 'seedphrase':
        default:
          this.$router.push('/onboarding/home')
          break
        case 'seedtype':
          this.currentStep = 'seedphrase'
          break
        case 'derivationpath':
          this.currentStep = 'seedtype'
          break
      }
    },
    next() {
      switch (this.currentStep) {
        case 'seedphrase':
          this.currentStep = 'seedtype'
          break
        case 'seedtype':
          if (this.seedtype === 'bip39_custom') {
            this.currentStep = 'derivationpath'
          } else {
            this.gotoSetup()
          }
          break
        case 'derivationpath':
        default:
          this.gotoSetup()
          break
      }
    },
    gotoSetup() {
      let derivationPath = undefined
      switch (this.seedtype) {
        case 'circbit':
          derivationPath = "m/84'/0'/0'"
          break
        case 'bip39_custom':
          derivationPath = this.customDerivationPath
        case 'bip39_standard':
        default:
            break

      }

      this.$router.push({
        name: 'OnboardingSetup',
        params: { seedphrase: this.mnemonic, derivationPath }
      })
    },
    setMnemonicLength(words) {
      this.numWords = words
      this.wordList = Array(this.numWords).fill('')
    }
  }
}
</script>

<style lang="scss">
.num-words {
  background: $color-text-primary;
}

.import-wallet {
  padding: 50px 0 0 0 !important;
  overflow-y: scroll;

  > div {
    padding: 0 $wrapper-padding;
  }

  .import-wallet_top {
    h2 {
      margin-bottom: 10px;
    }

    p {
      margin-bottom: 0 !important;
      font-size: $font-size-sm;
    }

    padding-top: 25px;
    padding-bottom: 20px;
  }

  .import-wallet_bottom {
    background: #ffffff;
    color: $color-text-primary;
    padding: $wrapper-padding;

    .btn-group {
      margin-bottom: 20px;
    }
  }

  .derivation-path-form-control {
    label {
      font-weight: bold;
      display: block;
      margin: 0.5rem 0;
    }

    input {
      display: block;
      width: 100%;
      border: 1px solid #ccc;
      font: inherit;
      line-height: 1.5rem;
      padding: 0 0.25rem;
      height: 2rem;
      align-items: center;
    }

    input:focus {
      outline: none;
      background: transparent;
      border-color: #3d3d3d;
    }

    .handlers {
      display: flex;
      flex-flow: row;
      gap: 10px;
      padding: 12px 0;
      width: 100%;
    }
  }

  &_icon {
    width: 40px;
    margin-top: 30px;
    margin-bottom: 10px;
  }

  h5 {
    color: $color-text-secondary;
  }

  &_seed.form {
    font-size: 18px;
    font-weight: 600;
    padding-left: 0;
    margin-bottom: 10px;
    text-align: left;
    counter-reset: wordIndex;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;

    div {
      display: block;
      flex: 0 0 94px;
      padding-bottom: 6px;
      text-align: left;

      &::before {
        display: block;
        font-size: $font-size-tiny;
        counter-increment: wordIndex;
        content: counter(wordIndex);
        font-weight: 600;
      }

      input {
        color: $color-text-primary;
        font-weight: 600;
      }
    }
  }
}
</style>
